version: 2.1

orbs:
  discord: antonioned/discord@0.1.0
  docker: circleci/docker@1.4.0

executors:
  docker-publisher:
    working_directory: ~/project/pineapple
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: decentm/pineapple

jobs:
  build:
    executor: docker-publisher

    steps:
      - setup_remote_docker
      - checkout

      - docker/build:
          cache_from: $IMAGE_NAME:latest
          image: $IMAGE_NAME

      - discord/status:
          fail_only: false

workflows:
  version: 2
  cd:
    jobs:
      - docker/publish:
          executor: docker-publisher
          use-remote-docker: true

          name: publish-latest
          filters:
            branches:
              only: master

          image: $IMAGE_NAME
          tag: latest
          cache_from: $IMAGE_NAME:latest
          update-description: true
          after_build:
            - discord/status:
              fail_only: false

      - docker/publish:
          executor: docker-publisher
          use-remote-docker: true

          name: publish-tagged
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

          image: $IMAGE_NAME
          tag: $CIRCLE_TAG
          cache_from: $IMAGE_NAME:latest
          update-description: true
          after_build:
            - discord/status:
              fail_only: false

      - build:
          name: build-branches
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /develop|GH-[0-9]{0,4}\/(fix|feat|chore|refactor|deps|build|ci|style|perf|test)\/.*/
