version: 2.1

executors:
  docker-publisher:
    working_directory: ~/project/pineapple
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_TAG: decentm/pineapple

jobs:
  build-latest:
    executor: docker-publisher

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_TAG:latest .

  # publish-latest:
  #   executor: docker-publisher

  #   steps:
  #     - setup_remote_docker:
  #         docker_layer_caching: true

  #     - run:
  #         name: Publish latest tag to Docker Hub
  #         command: |
  #           echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  #           docker push $IMAGE_TAG:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build-latest:
          filters:
            branches:
              only: master
