version: 2.1

orbs:
  discord: antonioned/discord@0.1.0
  docker: circleci/docker@1.4.0
  sentry-cli: picturepipe/sentry-cli@1.1.1

executors:
  docker-publisher:
    working_directory: ~/project/pineapple
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: decentm/pineapple

jobs:
  build:
    executor: docker-publisher

    steps:
      - setup_remote_docker
      - checkout

      - docker/build:
          cache_from: $IMAGE_NAME:latest
          image: $IMAGE_NAME

      - discord/status:
          fail_only: false

workflows:
  version: 2
  cd:
    jobs:
      #
      # Docker rolling release from master
      #
      - docker/publish:
          executor: docker-publisher
          use-remote-docker: true

          name: publish-latest
          filters:
            branches:
              only: master

          image: $IMAGE_NAME
          tag: latest
          cache_from: $IMAGE_NAME:latest
          update-description: true
          after_build:
            - discord/status:
              fail_only: false

      #
      # Docker production release from tags
      #
      - docker/publish:
          executor: docker-publisher
          use-remote-docker: true

          name: publish-tagged
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

          image: $IMAGE_NAME
          tag: $CIRCLE_TAG
          cache_from: $IMAGE_NAME:latest
          update-description: true
          after_build:
            - discord/status:
              fail_only: false

      #
      # Try to build every branch matching conventions
      # Branches: develop, and branches fitting this example: GH-12/feat/create-magic
      #
      - build:
          name: build-develop-branch
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /develop|GH-[0-9]{0,4}\/(fix|feat|chore|refactor|deps|build|ci|style|perf|test)\/.*/

  #
  # Sentry production release
  # (this will run parallel, even if the build fails)
  #
  sentry-tagged:
    jobs:
      # Load source code and determine release commits
      - sentry-cli/checkout-to-workspace:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - sentry-cli/set-version:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - sentry-cli/checkout-to-workspace

      # Send backend release to Sentry
      - sentry-cli/create-release:
          name: create-backend-release
          project: SENTRY_PROJECT_BACKEND
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - sentry-cli/set-version

      # Send frontend release to Sentry
      - sentry-cli/create-release:
          name: create-frontend-release
          project: SENTRY_PROJECT_FRONTEND
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - sentry-cli/set-version

      # Finalise and send release data
      - sentry-cli/finalize-release-set-commits:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - create-backend-release
            - create-frontend-release

      - sentry-cli/create-deployment:
          name: create-backend-deployment
          env: production
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - sentry-cli/finalize-release-set-commits
