version: "2.3"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432/tcp

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379/tcp
